import { DEFAULT_BOARD_SUBTITLE, DEFAULT_BOARD_TITLE, DEFAULT_STARTER_PROMPTS, defaultComposerPlaceholder } from "../core/constants.js";

/// 跨模块共享的状态：这里只留两个以上模块（或 settings.js 这类旧脚本经 ctx.state）
/// 都要读写的键。只有一个模块用的状态放在那个模块自己的 `xxxState` 里（P5 分片）。
export const state = {
  backgroundJobs: new Map(),
  expandedJobs: new Set(),
  jobStreamSinks: new Map(),
  latestEventId: 0,
  lastEventId: 0,
  replayRunIds: null,
  replayCutoff: 0,
  replayResyncCount: 0,
  replayResyncAt: 0,
  turns: [],
  queuedPrompts: [],
  models: [],
  persona: {
    name: "顾清影",
    avatar_url: "/assets/gqy-logo.png",
    board_image_url: "/assets/gqywallpaper.png",
    board_title: DEFAULT_BOARD_TITLE,
    board_subtitle: DEFAULT_BOARD_SUBTITLE,
    composer_placeholder: defaultComposerPlaceholder("GQY"),
    starter_prompts: DEFAULT_STARTER_PROMPTS
  },
  sessions: [],
  currentSessionId: null,
  viewSessionId: null,
  viewRunningTurnId: null,
  viewLoading: false,
  // 正在切往的会话:点击标签的瞬间就高亮它、并铺一层加载动画,等 turns 拉回来
  // 再真正应用视图(09-12 用户报「先加载后切换、点大会话像卡住」)。
  switchingToSessionId: "",
  runsBySession: new Map(),
  // 跑完了、但用户还没切进去看过的会话。
  // 「完成」不是能持续的状态（否则每个会话都会永远挂着「已完成」），
  // 「未读」才是——产生于回合结束，消失于用户切进那个会话。
  unreadSessions: new Set(),
  liveRuns: new Map(),
  // 输入框「累计」合成用(#131):cumulativeBase = 后端给的会话实时累计基线;
  // liveSubagentTokens = 正在跑的子代理各自的实时 token 估算,按 tool_id 存。
  cumulativeBase: null,
  liveSubagentTokens: new Map(),
  sessionMenuFor: null,
  sessionRenaming: null,
  lastReorderIds: "",
  modeChooserOpen: false,
  sessionBusy: false,
  display: {
    reasoning: "summary",
    tool_calls: "summary",
    readable_tool_names: true,
    command_output_lines: 10,
    mixed_model_endpoint_display: "interactive",
    show_mixed_model_endpoint: false
  },
  context: { tokens: 0, window: null },
  usage: {},
  capabilities: {},
  /// 登录者(阶段 5 多用户):{account_id, username, display_name, admin}。
  account: null,
  eventSource: null,
  blocked: false,
  adminBusy: false,
  sessionModelOverride: null,
  sessionModelOverrideFor: "",
  submitting: false,
  redoCandidate: null,
  pendingSubmission: null,
  composerAttachments: [],
  artifacts: [],
  selectedArtifactId: null,
  artifactOpen: false,
  artifactRenderToken: 0,
  artifactZoom: 1,
  artifactMode: "preview",
  artifactMaximized: false,
  artifactWidthRatio: 0.5,
  artifactSourceCache: new Map(),
  reasoningExpanded: false,
  toolExpanded: false,
  // 过程自动收起:她一开口,前面那串思考+工具收成一行总结。默认开。
  procCollapse: true,
  finishedTurnArticles: new Map(),
  bootstrapPromise: null,
  resyncing: false,
  nearBottom: true,
  followOutput: true,
  programmaticScroll: false,
  consolePanel: "usage",
  sidebarOpener: null,
  terminalRunIds: new Set(),
  thinkingVariantModels: [],
  settingsView: "interface",
  platformView: { platform: "qq", tab: "settings" },
  configLoaded: false,
  configLoading: false,
  configDraft: null,
  promptDraft: null,
  secretStates: {},
  secretChanges: {},
  providerSecretStates: [],
  configMultimodalModels: [],
  configInferredImageModels: [],
  invalidConfigFields: new Map()
};
