//! What lives under `GQY_HOME`, and whether it travels.
//!
//! Every path GQY writes must appear in [`UNITS`] — including the ones that
//! must *never* be exported. A hard-coded "list of things to back up" rots
//! silently: someone adds a feature, forgets the export path, and the user
//! only finds out on the new machine when the data is gone. Here the omission
//! is caught by `every_data_location_is_classified` instead.
//!
//! Adding a data location = adding one row. Deciding it should not travel is
//! still a row (`Tier::Never`) with the reason written down.

/// How a unit is copied.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UnitKind {
    File,
    Dir,
    /// Snapshotted with `VACUUM INTO` rather than copied: the daemon holds
    /// these open with a live WAL, so a plain copy can be torn or stale.
    Sqlite,
}

/// Which export tiers include a unit.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Tier {
    /// Exported by default.
    Core,
    /// Large and rebuildable; needs `--index`.
    Heavy,
    /// Platform conversation data; needs `--platforms`.
    Platform,
    /// Never exported. The `why` field says why.
    Never,
}

pub struct DataUnit {
    /// Stable identity, recorded in the manifest. Renaming `rel` must not
    /// change this — it is how a future build recognises an old archive.
    pub id: &'static str,
    /// Path relative to `GQY_HOME`. A trailing `/*` means "each child of this
    /// directory", used where the children are per-persona or per-platform.
    pub rel: &'static str,
    pub kind: UnitKind,
    pub tier: Tier,
    /// Carries credentials; `--no-secrets` redacts or drops it.
    pub secret: bool,
    /// Why this classification. Required for `Never` so a future reader can
    /// tell a deliberate exclusion from an oversight.
    pub why: &'static str,
}

pub const UNITS: &[DataUnit] = &[
    // ---- config ----------------------------------------------------------
    DataUnit {
        id: "config.main",
        rel: "config/config.jsonc",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: true,
        why: "provider api_key, qq access_token, plugin api_keys, mcp env",
    },
    DataUnit {
        id: "config.webui_theme",
        rel: "config/webui-theme.css",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "user-authored theme",
    },
    DataUnit {
        id: "config.webui_themes",
        rel: "config/webui-themes",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "WebUI theme library (Settings → Interface → Color scheme), written by \
              the user or the webui-theme skill",
    },
    DataUnit {
        id: "config.imessage",
        rel: "config/imessage.json",
        kind: UnitKind::File,
        tier: Tier::Platform,
        secret: false,
        why: "iMessage bridge settings; the contact list holds phone numbers and emails",
    },
    DataUnit {
        id: "config.shell_hooks",
        rel: "config/shell",
        kind: UnitKind::Dir,
        tier: Tier::Never,
        secret: false,
        why: "regenerated by `gqy bash-init` / `zsh-init`; the sourcing line \
               lives in the host's rc file, which we do not own",
    },
    // ---- data: user resources -------------------------------------------
    DataUnit {
        id: "data.prompts",
        rel: "data/prompts",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "persona prompts",
    },
    DataUnit {
        id: "data.identities",
        rel: "data/identities",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "user identities",
    },
    DataUnit {
        id: "data.persona_avatars",
        rel: "data/persona-avatars",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "persona avatars",
    },
    DataUnit {
        id: "data.skills",
        rel: "data/skills",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "user skills",
    },
    DataUnit {
        id: "data.scripts",
        rel: "data/scripts",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "user script tools",
    },
    DataUnit {
        id: "data.pictures",
        rel: "data/pictures",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "generated images",
    },
    DataUnit {
        id: "data.documents",
        rel: "data/documents",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "written output (reports and documents)",
    },
    DataUnit {
        id: "data.memes",
        rel: "data/memes",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "meme libraries",
    },
    // ---- data: memory ----------------------------------------------------
    DataUnit {
        id: "data.persona_memory",
        rel: "data/personas/*/memory/memory.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "long-term memory per persona scope",
    },
    // ---- data: ledger ----------------------------------------------------
    DataUnit {
        id: "data.ledger",
        rel: "data/ledger/ledger.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "personal ledger: books, accounts, categories, entries, budgets",
    },
    // ---- data: knowledge base -------------------------------------------
    DataUnit {
        id: "kb.files",
        rel: "data/kb/files",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "knowledge base source documents",
    },
    DataUnit {
        id: "kb.meta",
        rel: "data/kb/kb_meta.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "file index; its `files.path` column is absolute, so the import \
               summary tells the user to run `gqy kb reindex`",
    },
    DataUnit {
        id: "kb.semantic_index",
        rel: "data/kb/semantic_index.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Heavy,
        secret: false,
        why: "~143MB of embeddings derived from kb.files; `gqy kb embed` \
               rebuilds it, so it is opt-in via --index",
    },
    DataUnit {
        id: "kb.default_state",
        rel: "data/default-kb/state.json",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "default knowledge base version ledger",
    },
    // ---- data: platforms -------------------------------------------------
    DataUnit {
        id: "platform.message_history",
        rel: "data/platforms/*/message_history/history.sqlite3",
        kind: UnitKind::Sqlite,
        tier: Tier::Platform,
        secret: false,
        why: "group chat history; large and tied to one bot account, so opt-in",
    },
    DataUnit {
        id: "platform.plugin_data",
        rel: "data/platforms/*/real_context",
        kind: UnitKind::Dir,
        tier: Tier::Platform,
        secret: false,
        why: "platform plugin state, tied to the same account",
    },
    DataUnit {
        id: "data.artifacts",
        rel: "data/artifacts",
        kind: UnitKind::Dir,
        tier: Tier::Never,
        secret: false,
        why: "a disk projection of the artifact_assets BLOBs; the store \
               rebuilds it on the next turn, so shipping files would only \
               risk them disagreeing with the database",
    },
    // ---- state -----------------------------------------------------------
    DataUnit {
        id: "state.conversation",
        rel: "state/conversation.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "sessions, turns, image/attachment blobs, platform bindings",
    },
    DataUnit {
        id: "state.conversation_legacy",
        rel: "state/conversation.jsonl",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "pre-SQLite history, still read by the migration path",
    },
    DataUnit {
        id: "state.usage",
        rel: "state/usage.json",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "cumulative token usage",
    },
    DataUnit {
        id: "state.profile",
        rel: "state/profile.md",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "assistant profile notes",
    },
    DataUnit {
        id: "state.alarms",
        rel: "state/alarms.json",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "scheduled alarms",
    },
    DataUnit {
        id: "state.thinking_variants",
        rel: "state/thinking-variants.json",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "per-model thinking level choices",
    },
    DataUnit {
        id: "state.imessage_contacts",
        rel: "state/imessage-contacts.json",
        kind: UnitKind::File,
        tier: Tier::Platform,
        secret: false,
        why: "per-contact iMessage topic, model and pause choices",
    },
    DataUnit {
        id: "state.imessage_watermark",
        rel: "state/imessage-bridge.json",
        kind: UnitKind::File,
        tier: Tier::Never,
        secret: false,
        why: "ROWID watermark into this Mac's Messages chat.db; on another Mac the \
              numbers point at unrelated messages, so the bridge must start fresh",
    },
    DataUnit {
        id: "state.repl_history",
        rel: "state/repl-history.jsonl",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "REPL input history",
    },
    DataUnit {
        id: "state.skill_drafts",
        rel: "state/skill-drafts",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "in-progress skill drafts",
    },
    DataUnit {
        id: "state.evicted_context",
        rel: "state/personas/*/memory/evicted_context.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "context evicted from sessions, still searchable",
    },
    DataUnit {
        id: "state.aur_review",
        rel: "state/aur-review-state.json",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "package advisor review ledger",
    },
    DataUnit {
        id: "state.arch_news",
        rel: "state/arch_news_last_seen.json",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "last seen Arch news item",
    },
    DataUnit {
        id: "state.prompt_fingerprints",
        rel: "state/prompt-fingerprints",
        kind: UnitKind::Dir,
        tier: Tier::Never,
        secret: false,
        why: "per-session prompt hashes; a stale one only forces one extra \
               cold prompt rebuild, and carrying them risks the opposite",
    },
    DataUnit {
        id: "state.prompt_fingerprint_legacy",
        rel: "state/prompt.sha256",
        kind: UnitKind::File,
        tier: Tier::Never,
        secret: false,
        why: "same, single-file legacy form",
    },
    DataUnit {
        id: "state.daemon_launch",
        rel: "state/daemon-launch.json",
        kind: UnitKind::File,
        tier: Tier::Never,
        secret: true,
        why: "this machine's port/bind plus an absolute path to a password \
               file that does not exist on the target",
    },
    DataUnit {
        id: "state.web_passwords",
        rel: "state/web-passwords",
        kind: UnitKind::Dir,
        tier: Tier::Never,
        secret: true,
        why: "plaintext WebUI passwords in files named after this machine's pid",
    },
    DataUnit {
        id: "state.runtime_fallback",
        rel: "state/gqy",
        kind: UnitKind::Dir,
        tier: Tier::Never,
        secret: false,
        why: "socket/lock/job ledger fallback when XDG_RUNTIME_DIR is unset",
    },
    DataUnit {
        id: "state.conversation_backup",
        rel: "state/conversation.db.bak",
        kind: UnitKind::File,
        tier: Tier::Never,
        secret: false,
        why: "pre-migration copy; the live database is exported instead",
    },
    // ---- cache -----------------------------------------------------------
    DataUnit {
        id: "cache.all",
        rel: "cache",
        kind: UnitKind::Dir,
        tier: Tier::Never,
        secret: false,
        why: "logs, model cache, background-job logs, clipboard scratch, \
               platform images, AUR sandboxes, default-kb git clone — all \
               regenerated on demand and ~364MB of it",
    },
    DataUnit {
        id: "data.shared",
        rel: "data/shared",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "WebUI share hosting (snapshot mode and page uploads)",
    },
    DataUnit {
        id: "data.persona_memes",
        rel: "data/personas/*/meme.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "per-persona meme index",
    },
    DataUnit {
        id: "data.persona_manifest",
        rel: "data/personas/*/persona.toml",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "per-persona enable set (subsystems / plugins)",
    },
    // ---- home layout (09-10 stage 6): personas/ extensions/ home/<user>/ --
    DataUnit {
        id: "personas.memory",
        rel: "personas/*/memory/memory.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "long-term memory per shared persona (home layout)",
    },
    DataUnit {
        id: "personas.memes",
        rel: "personas/*/meme.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "per-persona meme index (home layout)",
    },
    DataUnit {
        id: "personas.manifest",
        rel: "personas/*/persona.toml",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "per-persona enable set (home layout)",
    },
    DataUnit {
        id: "extensions.skills",
        rel: "extensions/skills",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "installed skills (home layout)",
    },
    DataUnit {
        id: "extensions.scripts",
        rel: "extensions/scripts",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "installed scripts (home layout)",
    },
    DataUnit {
        id: "home.profile",
        rel: "home/*/profile.md",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "how the AI should know this person (owner-class entries only)",
    },
    DataUnit {
        id: "home.identities",
        rel: "home/*/identities",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "per-persona user identities that moved with the owner",
    },
    DataUnit {
        id: "home.conversation",
        rel: "home/*/conversation.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "sessions, turns, blobs, platform bindings, accounts (home layout)",
    },
    DataUnit {
        id: "home.pictures",
        rel: "home/*/pictures",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "generated and fetched images (home layout)",
    },
    DataUnit {
        id: "home.documents",
        rel: "home/*/documents",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "reports and other written output (home layout)",
    },
    DataUnit {
        id: "home.ledger",
        rel: "home/*/ledger/ledger.db",
        kind: UnitKind::Sqlite,
        tier: Tier::Core,
        secret: false,
        why: "personal ledger (home layout)",
    },
    DataUnit {
        id: "home.shares",
        rel: "home/*/shares",
        kind: UnitKind::Dir,
        tier: Tier::Core,
        secret: false,
        why: "WebUI share hosting (home layout)",
    },
    DataUnit {
        id: "home.artifacts",
        rel: "home/*/artifacts",
        kind: UnitKind::Dir,
        tier: Tier::Never,
        secret: false,
        why: "disk projection of artifact_assets BLOBs; rebuilt from the database",
    },
    // ---- layout markers --------------------------------------------------
    DataUnit {
        id: "layout.home_marker",
        rel: ".home-layout-v1",
        kind: UnitKind::File,
        tier: Tier::Core,
        secret: false,
        why: "names the admin home directory; travels so the restored tree \
               resolves home/<admin> the same way (an old archive without it \
               is migrated by GqyPaths::new on the next start)",
    },
    DataUnit {
        id: "layout.home_journal",
        rel: ".home-layout-v1.journal.json",
        kind: UnitKind::File,
        tier: Tier::Never,
        secret: false,
        why: "recovery journal for an interrupted home-layout migration",
    },
    DataUnit {
        id: "layout.markers",
        rel: ".layout-v1",
        kind: UnitKind::File,
        tier: Tier::Never,
        secret: false,
        why: "written by GqyPaths::new on the target; import stamps them so \
               the restored tree is not mistaken for an old layout",
    },
    DataUnit {
        id: "layout.resource_markers",
        rel: ".resource-layout-v1",
        kind: UnitKind::File,
        tier: Tier::Never,
        secret: false,
        why: "marks that skills/scripts/prompts already sit under data/; \
               import stamps it so the restored tree is not migrated again",
    },
    DataUnit {
        id: "layout.resource_journal",
        rel: ".resource-layout-v1.journal.json",
        kind: UnitKind::File,
        tier: Tier::Never,
        secret: false,
        why: "recovery journal for an interrupted layout migration; \
               meaningless on the target",
    },
];

/// Suffixes that are never their own unit: SQLite sidecars are folded into the
/// snapshot of their database, and editor/backup droppings are noise.
pub const IGNORED_SUFFIXES: &[&str] = &["-wal", "-shm", ".bak", ".tmp", ".lock"];

/// True when `name` is a backup dropping like `config.jsonc.bak-20260802-011956`.
pub fn is_backup_name(name: &str) -> bool {
    name.contains(".bak")
}

impl DataUnit {
    /// Whether this unit is included for the given tier switches.
    pub fn included(&self, all: bool, index: bool, platforms: bool) -> bool {
        match self.tier {
            Tier::Never => false,
            Tier::Core => true,
            Tier::Heavy => all || index,
            Tier::Platform => all || platforms,
        }
    }

    /// Path segments of `rel`, with `*` marking a wildcard level.
    pub fn segments(&self) -> impl Iterator<Item = &'static str> {
        self.rel.split('/')
    }
}

/// Finds the unit that claims `rel` (a path relative to `GQY_HOME`), matching
/// `*` against any single segment. A path under a directory unit is claimed by
/// that unit.
pub fn unit_for(rel: &str) -> Option<&'static DataUnit> {
    let parts: Vec<&str> = rel.split('/').filter(|part| !part.is_empty()).collect();
    UNITS.iter().find(|unit| {
        let pattern: Vec<&str> = unit.segments().collect();
        // A directory unit claims everything beneath it, so the path may be
        // longer than the pattern; it may never be shorter.
        if parts.len() < pattern.len() {
            return false;
        }
        pattern
            .iter()
            .zip(parts.iter())
            .all(|(want, have)| *want == "*" || want == have)
    })
}
