use super::PlatformTurnContext;
use crate::platform_types::{ConversationKind, OutboundMessage, OutboundOrigin, OutboundSegment};
use crate::tools::{ToolRegistry, ToolSpec};
use anyhow::{bail, Context, Result};
use serde_json::{json, Value};
use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::sync::Arc;
const MAX_TOOL_IMAGES: usize = 4;
const MAX_TOOL_FILES: usize = 4;
const MAX_TOOL_MENTIONS: usize = 32;

pub(crate) fn register(registry: &mut ToolRegistry, context: Arc<PlatformTurnContext>) {
    if context.conversation.kind == ConversationKind::Group {
        register_mention(registry, context.clone());
    }
    register_usage_query(registry, context.clone());
    // 赞助记账。写限管理员(软拒绝),看开放;懒加载,full 模式照样全量给出。
    super::sponsor_tool::register(registry, context.clone());
    // 资料卡点赞:只在白名单私聊/群里出现,只给请求者本人点。
    super::profile_like::register(registry, context.clone());
    if crate::web::voice_bridge::tts_available() {
        register_voice_message(registry, context.clone());
    }
    let host_tools_allowed = context.host_tools_allowed();
    let parameters = if host_tools_allowed {
        json!({
            "type": "object",
            "properties": {
                "text": { "type": "string", "description": "Optional text or Markdown." },
                "images": {
                    "type": "array",
                    "maxItems": MAX_TOOL_IMAGES,
                    "items": {
                        "type": "object",
                        "properties": {
                            "path": { "type": "string" },
                            "alt": { "type": "string" }
                        },
                        "required": ["path"],
                        "additionalProperties": false
                    }
                },
                "files": {
                    "type": "array",
                    "maxItems": MAX_TOOL_FILES,
                    "items": {
                        "type": "object",
                        "properties": {
                            "path": { "type": "string" },
                            "name": { "type": "string" }
                        },
                        "required": ["path"],
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        })
    } else {
        // 非管理员触发也能发 顾清影 自产的生成图(执行侧按生图目录校验豁免);
        // 任意本地文件仍只对管理员开放,所以这版没有 files。
        json!({
            "type": "object",
            "properties": {
                "text": { "type": "string", "description": "Optional text or Markdown." },
                "images": {
                    "type": "array",
                    "maxItems": MAX_TOOL_IMAGES,
                    "items": {
                        "type": "object",
                        "properties": {
                            "path": { "type": "string", "description": "Path of an image generated by a tool this turn (e.g. generate_image). Other local paths are rejected." },
                            "alt": { "type": "string" }
                        },
                        "required": ["path"],
                        "additionalProperties": false
                    }
                }
            },
            "additionalProperties": false
        })
    };
    registry.register(
        ToolSpec::new(
            "send_message_to_user",
            "Send text, local images, or local files to the current messaging-platform conversation.",
            parameters,
            move |arguments| {
                let context = context.clone();
                async move { send(arguments, context).await }
            },
        )
        .writes()
        .with_display_name("Send message"),
    );
}

/// `send_voice_message`:文本经播报供应商合成后作为 QQ 语音消息发到当前会话。
fn register_voice_message(registry: &mut ToolRegistry, context: Arc<PlatformTurnContext>) {
    registry.register(
        ToolSpec::new(
            "send_voice_message",
            "Send the given text as a spoken voice message (text-to-speech) to the current messaging-platform conversation.",
            json!({
                "type": "object",
                "properties": {
                    "text": { "type": "string", "description": "What to say, in natural spoken language (a few sentences at most)." }
                },
                "required": ["text"],
                "additionalProperties": false
            }),
            move |arguments| {
                let context = context.clone();
                async move {
                    let text = arguments
                        .get("text")
                        .and_then(Value::as_str)
                        .map(str::trim)
                        .unwrap_or_default()
                        .to_string();
                    if text.is_empty() {
                        bail!("text is required");
                    }
                    let path = crate::web::voice_bridge::synthesize_for_platform(&text).await?;
                    let outcome = context
                        .send(OutboundMessage::segments(
                            OutboundOrigin::Tool,
                            vec![OutboundSegment::AudioPath {
                                path: path.clone(),
                                transcript: text.clone(),
                            }],
                        ))
                        .await;
                    let _ = std::fs::remove_file(&path);
                    let receipt = outcome?;
                    // 语音已经发出去,回合末尾的正文不再单独发一条(09-06 用户:
                    // 「发了语音就没必要再发文字」)。与 send_message_to_user 的
                    // 直发抑制同一条路:tool.finished 时截掉此后的正文。
                    context
                        .pending_final_reply_suppression
                        .store(true, std::sync::atomic::Ordering::Release);
                    Ok(json!({
                        "ok": true,
                        "message_ids": receipt.message_ids,
                        "conversation": context.conversation.scope_key(),
                    })
                    .to_string())
                }
            },
        )
        .writes()
        .with_display_name("Send voice message"),
    );
}

fn register_mention(registry: &mut ToolRegistry, context: Arc<PlatformTurnContext>) {
    registry.register(
        ToolSpec::new(
            "qq_mention_users",
            "Natively @-mention one or more members in the next outgoing message of this group chat. Provide exact QQ ids; use get_group_members_info first when only names are known. This tool does not send a separate message.",
            json!({
                "type": "object",
                "properties": {
                    "user_ids": {
                        "type": "array",
                        "minItems": 1,
                        "maxItems": MAX_TOOL_MENTIONS,
                        "items": {
                            "type": "string",
                            "pattern": "^[1-9][0-9]{4,11}$"
                        },
                        "description": "Exact QQ IDs of the members to mention, in display order."
                    }
                },
                "required": ["user_ids"],
                "additionalProperties": false
            }),
            move |arguments| {
                let context = context.clone();
                async move { mention(arguments, &context).await }
            },
        )
        .writes()
        .with_display_name("Mention group members"),
    );
}

async fn mention(arguments: Value, context: &PlatformTurnContext) -> Result<String> {
    if context.conversation.kind != ConversationKind::Group {
        bail!("mentioning users is only available in a group conversation");
    }
    let object = arguments
        .as_object()
        .context("arguments must be an object containing only user_ids")?;
    if object.len() != 1 || !object.contains_key("user_ids") {
        bail!("only user_ids may be specified");
    }
    let raw_user_ids = array(&arguments, "user_ids")?;
    if raw_user_ids.is_empty() {
        bail!("user_ids must contain at least one QQ ID");
    }
    if raw_user_ids.len() > MAX_TOOL_MENTIONS {
        bail!("at most {MAX_TOOL_MENTIONS} users may be mentioned at once");
    }

    let mut seen = HashSet::new();
    let mut user_ids = Vec::with_capacity(raw_user_ids.len());
    for (index, value) in raw_user_ids.iter().enumerate() {
        let user_id = value
            .as_str()
            .filter(|user_id| !user_id.is_empty())
            .with_context(|| format!("user_ids[{index}] must be a QQ ID string"))?;
        if !(5..=12).contains(&user_id.len())
            || !user_id
                .as_bytes()
                .first()
                .is_some_and(|byte| matches!(byte, b'1'..=b'9'))
            || !user_id.bytes().all(|byte| byte.is_ascii_digit())
        {
            bail!("user_ids[{index}] must be a 5-12 digit QQ ID");
        }
        let user_id = user_id.to_string();
        if seen.insert(user_id.clone()) {
            user_ids.push(user_id);
        }
    }
    let member_ids = context
        .group_members()
        .await
        .context("looking up current group members before mentioning them")?
        .into_iter()
        .map(|member| member.user_id)
        .collect::<HashSet<_>>();
    let missing = user_ids
        .iter()
        .filter(|user_id| !member_ids.contains(*user_id))
        .cloned()
        .collect::<Vec<_>>();
    if !missing.is_empty() {
        bail!(
            "these QQ IDs are not members of the current group: {}",
            missing.join(", ")
        );
    }
    context.set_explicit_response_mentions(user_ids.clone());

    Ok(json!({
        "ok": true,
        "user_ids": user_ids,
        "conversation": context.conversation.scope_key(),
        "message": "The next outgoing message will mention these members. Write that message normally."
    })
    .to_string())
}

async fn send(arguments: Value, context: Arc<PlatformTurnContext>) -> Result<String> {
    let mut segments = Vec::new();
    let text_arg = arguments
        .get("text")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|text| !text.is_empty())
        .map(str::to_string);
    // 文字幂等闸(08-22 复读取证):与图片 digest 闸同语义。端点故障日模型
    // 会把"发送回复"重演成同义变体——本回合内近似文本直接拒发。
    let mut deduplicated_text = false;
    if let Some(text) = text_arg.as_deref() {
        if context.is_duplicate_reply_text(text) {
            deduplicated_text = true;
        } else {
            segments.push(OutboundSegment::Markdown(text.to_string()));
        }
    }
    let images = array(&arguments, "images")?;
    if images.len() > MAX_TOOL_IMAGES {
        bail!("at most {MAX_TOOL_IMAGES} images may be sent at once");
    }
    let files = array(&arguments, "files")?;
    if files.len() > MAX_TOOL_FILES {
        bail!("at most {MAX_TOOL_FILES} files may be sent at once");
    }
    let image_paths = images
        .iter()
        .map(|image| required_path(image, "path"))
        .collect::<Result<Vec<_>>>()?;
    if (!images.is_empty() || !files.is_empty()) && !context.host_tools_allowed() {
        // 附件门槛防的是把宿主上任意文件发给陌生人;顾清影 自己刚生成的图不在
        // 此列——平台生图已改为模型显式发送(08-20 裁定),没有这条豁免,
        // 非管理员触发的画图请求就永远发不出结果。
        // 08-22:get_avatar 改为"只下载不投递",发送权交还模型——头像缓存
        // 目录与生图目录同为 顾清影 自产内容,一并豁免。
        let avatar_dir = context.paths.cache_dir.join("qq-avatars");
        let exempt = files.is_empty()
            && !image_paths.is_empty()
            && (all_within_generated_dir(
                &context.config.plugins.image_generation.output_dir,
                &image_paths,
            ) || all_within_root(&avatar_dir, &image_paths));
        if !exempt {
            bail!("local attachments require an authorized platform administrator");
        }
    }
    // 幂等闸:本会话已投递过的图不再重复发送。LLM 端点失败重试会让模型把
    // 「发送这张图」的指引重演一遍(真机同图 4 连发),工具层按内容 digest
    // 兜底,与平台自动投递的去重同一语义。
    let mut skipped_duplicates = 0usize;
    let mut fresh = Vec::new();
    if !image_paths.is_empty() {
        let delivered = context.delivered_image_digests();
        for (image, path) in images.iter().zip(image_paths) {
            let duplicate = std::fs::read(&path)
                .ok()
                .map(|bytes| blake3::hash(&bytes))
                .is_some_and(|digest| delivered.contains(&digest));
            if duplicate {
                skipped_duplicates += 1;
            } else {
                fresh.push((image, path));
            }
        }
        if fresh.is_empty() && skipped_duplicates > 0 && files.is_empty() {
            return Ok(json!({
                "ok": true,
                "deduplicated": true,
                "message": "This image was already delivered to this conversation; the send is complete. Do not send it again."
            })
            .to_string());
        }
    }
    for (image, path) in fresh {
        let alt = image
            .get("alt")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .trim()
            .to_string();
        segments.push(OutboundSegment::ImagePath { path, alt });
    }
    for file in &files {
        let path = required_path(file, "path")?;
        let name = file
            .get("name")
            .and_then(Value::as_str)
            .map(str::trim)
            .filter(|name| !name.is_empty())
            .map(str::to_string);
        segments.push(OutboundSegment::FilePath { path, name });
    }
    if segments.is_empty() {
        if deduplicated_text || skipped_duplicates > 0 {
            return Ok(json!({
                "ok": true,
                "deduplicated": true,
                "message": "This reply was already delivered to this conversation; the send is complete. Do not send it again or a rephrased version of it."
            })
            .to_string());
        }
        bail!("text, images, or files is required");
    }
    let receipt = context
        .send(OutboundMessage::segments(OutboundOrigin::Tool, segments))
        .await?;
    if let Some(text) = text_arg.as_deref() {
        if !deduplicated_text {
            context.record_delivered_reply_text(text);
        }
    }
    Ok(json!({
        "ok": true,
        "message_ids": receipt.message_ids,
        "conversation": context.conversation.scope_key(),
    })
    .to_string())
}

fn array(arguments: &Value, key: &str) -> Result<Vec<Value>> {
    match arguments.get(key) {
        None | Some(Value::Null) => Ok(Vec::new()),
        Some(Value::Array(values)) => Ok(values.clone()),
        // 模型常把数组写成「数组的 JSON 字符串」(真机实测 mimo-v2.5 给
        // send_message_to_user 传的 images 就是这形态,补发图片被本行上一版
        // 的硬校验拦死)。与 generate_image.reference_images 同款宽松解析。
        Some(Value::String(text)) => match serde_json::from_str::<Value>(text) {
            Ok(Value::Array(values)) => Ok(values),
            _ => bail!("{key} must be an array"),
        },
        Some(_) => bail!("{key} must be an array"),
    }
}

/// 全部路径都落在生图输出目录内(符号链接经 canonicalize 展开,防目录
/// 逃逸)。目录不存在或路径解析失败一律按不豁免处理。
fn all_within_root(root: &std::path::Path, paths: &[PathBuf]) -> bool {
    let Ok(root) = root.canonicalize() else {
        return false;
    };
    !paths.is_empty()
        && paths.iter().all(|path| {
            path.canonicalize()
                .map(|canonical| canonical.starts_with(&root))
                .unwrap_or(false)
        })
}

fn all_within_generated_dir(output_dir: &str, paths: &[PathBuf]) -> bool {
    let expanded = if let Some(rest) = output_dir.strip_prefix("~/") {
        match std::env::var_os("HOME") {
            Some(home) => PathBuf::from(home).join(rest),
            None => return false,
        }
    } else {
        PathBuf::from(output_dir)
    };
    let Ok(root) = expanded.canonicalize() else {
        return false;
    };
    !paths.is_empty()
        && paths.iter().all(|path| {
            path.canonicalize()
                .map(|canonical| canonical.starts_with(&root))
                .unwrap_or(false)
        })
}

fn required_path(value: &Value, key: &str) -> Result<PathBuf> {
    let raw = value
        .get(key)
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|path| !path.is_empty())
        .with_context(|| format!("{key} is required"))?;
    let path = if let Some(home) = raw.strip_prefix("~/") {
        std::env::var_os("HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("~"))
            .join(home)
    } else {
        PathBuf::from(raw)
    };
    let path = if path.is_absolute() {
        path
    } else {
        crate::tools::workspace::effective_workdir().join(path)
    };
    let metadata = std::fs::metadata(&path)
        .with_context(|| format!("reading attachment metadata: {}", path.display()))?;
    if !metadata.is_file() {
        bail!("attachment is not a regular file: {}", path.display());
    }
    Ok(Path::new(&path).to_path_buf())
}

/// 平台侧的 token 消耗查询:读 usage-history 聚合出适合聊天气泡的摘要。
/// 口径与 WebUI 控制台一致——智能体与各平台的全部 LLM 请求都在账上。
fn register_usage_query(registry: &mut ToolRegistry, context: Arc<PlatformTurnContext>) {
    registry.register(
        ToolSpec::new(
            "query_token_usage",
            crate::tools::usage_query::DESCRIPTION,
            crate::tools::usage_query::parameters(),
            move |arguments| {
                let context = context.clone();
                async move { query_token_usage(arguments, context).await }
            },
        )
        .with_display_name("Token usage"),
    );
}

async fn query_token_usage(arguments: Value, context: Arc<PlatformTurnContext>) -> Result<String> {
    let range_key = arguments
        .get("range")
        .and_then(Value::as_str)
        .unwrap_or("1d")
        .to_string();
    let range = crate::state::UsageRange::parse(&range_key);
    let store = context.state_store.clone();
    let config = context.config.clone();
    let stats = tokio::task::spawn_blocking(move || store.usage_stats(range, Some(&config)))
        .await
        .context("usage stats task panicked")??;
    Ok(crate::tools::usage_query::format_usage_summary(
        &stats, &range_key,
    ))
}

#[cfg(test)]
mod argument_shape_tests {
    use super::*;

    /// 模型把 images 数组写成 JSON 字符串是真机高频形态(mimo-v2.5 实测),
    /// 必须与真数组同样接受;垃圾字符串仍要报错。
    #[test]
    fn stringified_json_arrays_are_accepted() {
        let arguments = serde_json::json!({
            "images": "[{\"alt\": \"自画像\", \"path\": \"/tmp/a.png\"}]"
        });
        let images = array(&arguments, "images").unwrap();
        assert_eq!(images.len(), 1);
        assert_eq!(images[0]["path"], "/tmp/a.png");

        let real = serde_json::json!({ "images": [{ "path": "/tmp/b.png" }] });
        assert_eq!(array(&real, "images").unwrap().len(), 1);

        assert!(array(&serde_json::json!({ "images": "not json" }), "images").is_err());
        assert!(array(&serde_json::json!({ "images": 3 }), "images").is_err());
        assert!(array(&serde_json::json!({}), "images").unwrap().is_empty());
    }
}

#[cfg(test)]
mod generated_dir_exemption_tests {
    use super::*;

    /// 生图目录内的图豁免管理员附件门槛;目录外与逃逸路径不豁免。
    #[test]
    fn only_generated_images_are_exempt() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("generated-images");
        std::fs::create_dir_all(&root).unwrap();
        let inside = root.join("a.png");
        std::fs::write(&inside, b"x").unwrap();
        let outside = dir.path().join("secret.txt");
        std::fs::write(&outside, b"x").unwrap();
        let root_str = root.display().to_string();
        assert!(all_within_generated_dir(&root_str, &[inside.clone()]));
        assert!(!all_within_generated_dir(&root_str, &[outside.clone()]));
        assert!(!all_within_generated_dir(&root_str, &[inside, outside]));
        assert!(!all_within_generated_dir(&root_str, &[]));
        assert!(!all_within_generated_dir(
            &root_str,
            &[root.join("../secret.txt")]
        ));
    }
}
