// ---------------------------------------------------------------------
// 通用设置(path = 从配置根开始的完整点路径)
// ---------------------------------------------------------------------
const general = [
  {
    id: "tools",
    title: "工具",
    tab: "工具",
    fields: [
      { path: "tools.enabled", label: "工具启用", kind: "toggle", default: true },
      {
        path: "tools.max_rounds",
        label: "工具最大轮数",
        hint: "本机会话一回合最多工具轮数,0 = 不限",
        kind: "number",
        integer: true,
        min: 0,
        unit: "轮",
        default: 0,
      },
      {
        path: "tools.loading_mode",
        label: "工具加载模式",
        hint: "full 全量注入契约;stub 空壳按需加载省 token",
        kind: "select",
        choices: [
          { value: "full", label: "全量(full)" },
          { value: "stub", label: "需加载(stub)" },
        ],
        default: "full",
      },
      {
        path: "tools.persist_loaded_tools",
        label: "记住已加载工具",
        hint: "stub 模式下已加载的工具跨会话保留",
        kind: "toggle",
        default: true,
      },
      {
        path: "tools.subagent_concurrency",
        label: "子代理并发数",
        hint: "同一批 task 子代理最多同时跑几个",
        kind: "number",
        integer: true,
        min: 1,
        default: 4,
      },
      {
        path: "tools.default_timeout_secs",
        label: "工具兜底超时",
        hint: "没有自管超时的工具(MCP/网页等)统一上限,0 = 关闭",
        kind: "number",
        integer: true,
        min: 0,
        unit: "秒",
        default: 180,
      },
      {
        path: "tools.command_deny",
        label: "命令拒绝子串",
        hint: "run_command 命中即拒,防提示注入与手滑",
        kind: "string-list",
        default: ["rm -rf /", "rm -rf ~", "mkfs.", "dd if=/dev/zero of=/dev/", ":(){ :|:& };:"],
      },
      {
        path: "tools.sandbox.writable",
        label: "沙盒额外可写",
        hint: "/sandbox 绑定后根之外还能写的目录(构建缓存);改了会掰一次缓存",
        kind: "string-list",
        default: ["~/.cargo", "~/.npm"],
      },
      {
        path: "tools.sandbox.readable",
        label: "沙盒额外只读",
        hint: "/sandbox 绑定后根之外还能读的目录或文件(工具链);~/.ssh 这类别放",
        kind: "string-list",
        default: ["~/.rustup", "~/.local", "~/.gitconfig"],
      },
    ],
  },
  {
    id: "skills",
    title: "Skills",
    tab: "工具",
    fields: [
      { path: "skills.enabled", label: "Skills 启用", kind: "toggle", default: true },
      {
        path: "skills.allow_command_execution",
        label: "允许执行命令",
        hint: "允许技能脚本执行本机命令",
        kind: "toggle",
        default: true,
      },
    ],
  },
  {
    id: "mcp",
    title: "MCP",
    custom: "mcp_servers",
    fields: [
      {
        path: "mcp.enabled",
        label: "MCP 启用",
        hint: "服务器列表由专用编辑器管理",
        kind: "toggle",
        default: false,
      },
    ],
  },
  {
    id: "display",
    title: "显示",
    tab: "对话",
    fields: [
      {
        path: "display.language",
        label: "界面语言",
        kind: "select",
        choices: [
          { value: "auto", label: "自动" },
          { value: "en", label: "英语" },
          { value: "zh", label: "简体中文" },
        ],
        default: "auto",
      },
      {
        path: "display.reasoning",
        label: "显示思考过程",
        kind: "select",
        choices: REASONING_CHOICES,
        default: "summary",
      },
      {
        path: "display.tool_calls",
        label: "显示工具调用信息",
        kind: "select",
        choices: REASONING_CHOICES,
        default: "summary",
      },
      {
        path: "display.readable_tool_names",
        label: "工具名可读显示",
        kind: "toggle",
        default: true,
      },
      {
        path: "display.show_token_usage",
        label: "Shell 无缝对话显示 Token 计数",
        kind: "toggle",
        default: false,
      },
      {
        path: "display.mixed_model_endpoint_display",
        label: "Mixed 时显示本次供应商/模型",
        kind: "select",
        choices: [
          { value: "off", label: "关" },
          { value: "interactive", label: "仅交互模式" },
          { value: "all", label: "全部模式" },
        ],
        default: "interactive",
      },
      {
        path: "display.command_output_lines",
        label: "命令输出显示行数",
        kind: "number",
        integer: true,
        min: 0,
        max: 1000,
        unit: "行",
        default: 10,
      },
      {
        path: "display.repl_replay_turns",
        label: "回到上次会话时回放的轮数",
        hint: "只在 gqy -c 回到上次会话时生效；0 = 不回放",
        kind: "number",
        integer: true,
        min: 0,
        max: 20,
        unit: "轮",
        default: 3,
      },
      {
        path: "display.mascot",
        label: "开屏吉祥物",
        hint: "终端开屏欢迎框里画什么;立绘在 16 色终端画不出时自动换黑猫",
        kind: "select",
        choices: [
          { value: "portrait", label: "顾清影立绘" },
          { value: "cat", label: "黑猫字符画" },
          { value: "custom", label: "自定义(config/banner.txt)" },
          { value: "off", label: "不画" },
        ],
        default: "portrait",
      },
      {
        path: "display.theme",
        label: "终端底色",
        hint: "影响代码高亮、diff 等内容色，界面色跟终端配色走",
        kind: "select",
        choices: [
          { value: "auto", label: "自动检测" },
          { value: "dark", label: "深色" },
          { value: "light", label: "浅色" },
        ],
        default: "auto",
      },
    ],
  },
  {
    id: "context",
    title: "上下文",
    tab: "对话",
    fields: [
      {
        path: "context.on_overflow",
        label: "上下文到达上限后",
        kind: "select",
        choices: OVERFLOW_CHOICES,
        default: "compact",
      },
      {
        path: "context.default_context_window",
        label: "默认上下文窗口",
        hint: "模型没报窗口大小时用的通用常数",
        kind: "number",
        integer: true,
        min: 1,
        unit: "token",
        default: 168000,
      },
      {
        path: "context.tool_output_spill_bytes",
        label: "工具输出外溢阈值",
        hint: "超限的工具输出落盘,模型只看头尾预览;0 = 关闭",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字节",
        default: 50000,
      },
      {
        path: "context.compact_cache_reuse",
        label: "摘要复用前缀缓存",
        hint: "按请求计费的网关关掉,改走独立摘要路径",
        kind: "toggle",
        default: true,
      },
      {
        path: "context.compact_restore_files",
        label: "压缩后回灌文件数",
        hint: "压完把最近碰过的文件从盘上重读回上下文;0 = 关闭",
        kind: "number",
        integer: true,
        min: 0,
        unit: "个",
        default: 5,
      },
      {
        path: "context.compact_restore_file_tokens",
        label: "回灌单文件上限",
        hint: "超过就只留路径,模型按需自己读回",
        kind: "number",
        integer: true,
        min: 0,
        unit: "token",
        default: 4000,
      },
      {
        path: "context.compact_restore_total_tokens",
        label: "回灌总预算",
        hint: "一次压缩回灌的总量,还会再受上下文窗口八分之一封顶",
        kind: "number",
        integer: true,
        min: 0,
        unit: "token",
        default: 24000,
      },
      {
        path: "context.compact_transcript_export",
        label: "导出折叠原文",
        hint: "把被折叠的对话写成 Markdown 存盘,摘要漏掉的细节她能读回来",
        kind: "toggle",
        default: true,
      },
    ],
    advanced: [
      {
        path: "context.trim_at_ratio",
        label: "压缩触发水位",
        hint: "0.1–1.0;须 ≤ 强制压缩水位",
        kind: "number",
        min: 0.1,
        max: 1.0,
        step: 0.01,
        default: 0.8,
      },
      {
        path: "context.compact_force_ratio",
        label: "强制压缩水位",
        hint: "≥ 压缩触发水位",
        kind: "number",
        min: 0.1,
        max: 1.0,
        step: 0.01,
        default: 0.9,
      },
      {
        path: "context.trim_batch_ratio",
        label: "单次修剪比例",
        hint: "pop 模式一次让出的窗口占比",
        kind: "number",
        min: 0.01,
        max: 0.9,
        step: 0.01,
        default: 0.15,
      },
      {
        path: "context.compact_tail_tokens",
        label: "摘要后保留尾部",
        hint: "留空 = 自动(任务模式 min(16384, 窗口/4),聊天 8192)",
        kind: "number",
        integer: true,
        min: 0,
        nullable: true,
        unit: "token",
        default: null,
      },
      {
        path: "context.tool_result_prune_chars",
        label: "工具结果剪枝阈值",
        hint: "落库时超过此字符数改写成头+尾;0 = 关闭",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字符",
        default: 8192,
      },
      {
        path: "context.tool_result_prune_head_chars",
        label: "剪枝保留头部",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字符",
        default: 4096,
      },
      {
        path: "context.tool_result_prune_tail_chars",
        label: "剪枝保留尾部",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字符",
        default: 1024,
      },
    ],
  },
  {
    id: "memory",
    title: "记忆",
    tab: "记忆",
    // 注意:AppConfig.memory 是 skip_serializing,WebUI 编辑 plugins.memory.*
    fields: [
      { path: "plugins.memory.enabled", label: "启用", kind: "toggle", default: true },
      {
        path: "plugins.memory.evicted_context_enabled",
        label: "上下文弹出缓存",
        hint: "被修剪出窗口的内容存档可召回",
        kind: "toggle",
        default: true,
      },
      {
        path: "plugins.memory.association_enabled",
        label: "联想启用",
        hint: "回合开始时自动注入相关记忆",
        kind: "toggle",
        default: true,
      },
      {
        path: "plugins.memory.auto_diary_enabled",
        label: "自动日记",
        kind: "toggle",
        default: true,
      },
      {
        path: "plugins.memory.auto_fact_enabled",
        label: "自动知识记忆",
        kind: "toggle",
        default: true,
      },
      {
        path: "plugins.memory.association_dedup",
        label: "联想跨回合去重",
        hint: "已在本会话注入过的记忆不再重复注入",
        kind: "toggle",
        default: true,
      },
      {
        path: "plugins.memory.forgetting_enabled",
        label: "遗忘启用",
        kind: "toggle",
        default: true,
      },
      {
        path: "plugins.memory.auto_skill_enabled",
        label: "自动技能沉淀",
        hint: "TUI 固定关闭;仅保留字段",
        kind: "toggle",
        hidden: true,
        default: false,
      },
    ],
    advanced: [
      {
        path: "plugins.memory.diary_batch_size",
        label: "日记整理轮数",
        hint: "累计多少轮触发一次日记整理",
        kind: "number",
        integer: true,
        min: 2,
        max: 100,
        unit: "轮",
        default: 14,
      },
      {
        path: "plugins.memory.short_diary_retention_days",
        label: "短期日记保留天数",
        kind: "number",
        integer: true,
        min: 1,
        max: 3650,
        unit: "天",
        default: 14,
      },
      {
        path: "plugins.memory.diary_promotion_recalls",
        label: "日记长期化召回次数",
        hint: "被召回多少次后升为长期记忆",
        kind: "number",
        integer: true,
        min: 1,
        max: 100,
        unit: "次",
        default: 3,
      },
      {
        path: "plugins.memory.organizer_timeout_seconds",
        label: "记忆整理超时秒数",
        kind: "number",
        integer: true,
        min: 5,
        max: 600,
        unit: "秒",
        default: 120,
      },
      {
        path: "plugins.memory.review_idle_seconds",
        label: "聊后复盘等待秒数",
        hint: "对话安静这么久后，她在后台复盘这段对话，下一轮起按复盘结果调整。0 关闭，最少 300",
        kind: "number",
        integer: true,
        min: 0,
        max: 86400,
        unit: "秒",
        default: 900,
      },
      {
        path: "plugins.memory.association_facts",
        label: "联想知识条数",
        kind: "number",
        integer: true,
        min: 0,
        unit: "条",
        default: 2,
      },
      {
        path: "plugins.memory.association_episodes",
        label: "联想事件条数",
        kind: "number",
        integer: true,
        min: 0,
        unit: "条",
        default: 1,
      },
      {
        path: "plugins.memory.association_max_chars",
        label: "联想字符上限",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字符",
        default: 1800,
      },
      {
        path: "plugins.memory.association_entry_chars",
        label: "单条联想正文上限",
        hint: "超长条目截断并带 id,0 = 不截断",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字符",
        default: 120,
      },
      {
        path: "plugins.memory.snippet_chars",
        label: "记忆片段字数",
        hint: "recall 工具返回的片段长度",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字符",
        default: 500,
      },
      {
        path: "plugins.memory.forget_after_days",
        label: "遗忘期限",
        hint: "超过此天数未被召回的记忆可被遗忘",
        kind: "number",
        integer: true,
        min: 1,
        unit: "天",
        default: 90,
      },
      {
        path: "plugins.memory.forgetting_half_life_days",
        label: "遗忘半衰期天",
        kind: "number",
        min: 0.01,
        step: 0.5,
        unit: "天",
        default: 7.0,
      },
      {
        path: "plugins.memory.forgetting_min_strength",
        label: "遗忘最低强度",
        hint: "强度低于此值的记忆被遗忘",
        kind: "number",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.15,
      },
      {
        path: "plugins.memory.forgetting_review_boost",
        label: "回忆增强强度",
        hint: "每次召回给记忆强度加多少",
        kind: "number",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.35,
      },
      {
        path: "plugins.memory.learning_min_task_chars",
        label: "学习任务最短字数",
        hint: "任务描述短于此不沉淀方法记忆",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字符",
        default: 16,
      },
      {
        path: "plugins.memory.learning_min_method_chars",
        label: "学习方法最短字数",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字符",
        default: 120,
      },
    ],
  },
  {
    id: "voice",
    title: "语音功能",
    tab: "语音与通知",
    description:
      "麦克风常开的唤醒词对话与听写。识别在本机独立的 gqy-voice 进程里跑,关着时零占用;" +
      "首次启用会下载约 190MB 识别模型。改动需重载配置生效。",
    fields: [
      {
        path: "voice.enabled",
        label: "语音唤醒",
        hint: "麦克风常开、唤醒词、听写。需要安装 gqy-voice;与文本转语音独立",
        kind: "toggle",
        default: false,
      },
      {
        path: "voice.microphone",
        label: "麦克风",
        hint: "列表来自 PipeWire 的输入源(与系统设置里一致);拔掉的设备仍保留当前值",
        kind: "select",
        choices: [{ value: "", label: "系统默认" }],
        choicesFrom: { url: "/api/voice/devices", key: "devices" },
        default: "",
      },
      {
        path: "voice.wake_threshold",
        label: "唤醒阈值",
        hint: "越低越灵敏也越易误唤醒",
        kind: "number",
        min: 0.01,
        max: 1,
        step: 0.01,
        default: 0.25,
      },
      {
        path: "voice.wake_boost",
        label: "唤醒词加分",
        hint: "越大越灵敏",
        kind: "number",
        min: 0,
        max: 10,
        step: 0.1,
        default: 1,
      },
      {
        path: "voice.stt_threads",
        label: "本地识别线程数",
        kind: "number",
        integer: true,
        min: 1,
        max: 8,
        default: 2,
      },
      {
        path: "voice.stt_language",
        label: "识别语言",
        hint: "固定「中文」可避免环境噪声被认成日文碎片",
        kind: "select",
        choices: [
          { value: "auto", label: "自动" },
          { value: "zh", label: "中文" },
          { value: "en", label: "英文" },
          { value: "ja", label: "日文" },
          { value: "ko", label: "韩文" },
          { value: "yue", label: "粤语" },
        ],
        default: "zh",
      },
      {
        path: "voice.stt_unload_seconds",
        label: "识别模型闲置卸载",
        hint: "0 = 常驻(快但多占 ~300MB 内存)",
        kind: "number",
        integer: true,
        min: 0,
        unit: "秒",
        default: 60,
      },
      {
        path: "voice.follow_up_seconds",
        label: "免唤醒追问窗口",
        hint: "她回复完(播报播完)起算,这段时间内说话不用再喊唤醒词;每次回复重新起算;0 = 关",
        kind: "number",
        integer: true,
        min: 0,
        unit: "秒",
        default: 30,
      },
      {
        path: "voice.min_utterance_chars",
        label: "最少有效字数",
        hint: "识别文本少于此数视为噪声丢弃",
        kind: "number",
        integer: true,
        min: 0,
        default: 2,
      },
      { path: "voice.sounds", label: "提示音", kind: "toggle", default: true },
      {
        path: "voice.sound_volume",
        label: "提示音音量",
        kind: "number",
        min: 0,
        max: 1,
        step: 0.05,
        default: 0.6,
        showWhen: { key: "voice.sounds", value: true },
      },
      {
        path: "voice.tts.enabled",
        label: "文本转语音",
        hint: "唤醒对话的回复合成成语音播出;也给模型提供 speak 工具主动说话。与语音唤醒独立,任一开启都会运行 gqy-voice",
        kind: "toggle",
        default: false,
      },
      {
        path: "voice.tts.active",
        label: "播报供应商",
        hint: "播报供应商独立配置,不共用 LLM 供应商",
        kind: "select",
        choices: [
          { value: "", label: "默认(MiniMax)" },
          { value: "minimax", label: "MiniMax" },
          { value: "mimo", label: "Xiaomi MiMo" },
        ],
        default: "",
        nullable: true,
        showWhen: { key: "voice.tts.enabled", value: true },
      },
      {
        path: "voice.tts.minimax.api_key",
        label: "MiniMax API key",
        hint: "账号级 key,对话与语音共用;支持 $env:VAR 引用",
        kind: "text",
        mono: true,
        default: "",
        nullable: true,
        showWhen: { key: "voice.tts.active", value: ["", "minimax"] },
      },
      {
        path: "voice.tts.minimax.base_url",
        label: "MiniMax 接口地址",
        kind: "select",
        choices: [
          { value: "https://api.minimaxi.com/v1", label: "国内站 api.minimaxi.com" },
          { value: "https://api.minimax.io/v1", label: "国际站 api.minimax.io" },
        ],
        default: "https://api.minimaxi.com/v1",
        showWhen: { key: "voice.tts.active", value: ["", "minimax"] },
      },
      {
        path: "voice.tts.minimax.model",
        label: "MiniMax 模型",
        hint: "turbo 首包快,hd 音质好",
        kind: "select",
        choices: [
          "speech-2.8-hd", "speech-2.8-turbo", "speech-2.6-hd", "speech-2.6-turbo",
          "speech-02-hd", "speech-02-turbo", "speech-01-hd", "speech-01-turbo",
        ],
        default: "speech-2.6-turbo",
        showWhen: { key: "voice.tts.active", value: ["", "minimax"] },
      },
      {
        path: "voice.tts.minimax.voice_id",
        label: "MiniMax 音色",
        hint: "列表按已保存的 key 从 MiniMax 拉取(含克隆音色);先保存 key 再刷新页面。TUI 里可搜索、按标签筛选并试听",
        kind: "select",
        choices: [],
        choicesFrom: { url: "/api/voice/tts/voices?provider=minimax", key: "voices" },
        default: "Chinese_sweet_girl_nv1",
        showWhen: { key: "voice.tts.active", value: ["", "minimax"] },
      },
      {
        path: "voice.tts.minimax.speed",
        label: "语速",
        kind: "number",
        min: 0.5,
        max: 2,
        step: 0.1,
        default: 1,
        showWhen: { key: "voice.tts.active", value: ["", "minimax"] },
      },
      {
        path: "voice.tts.minimax.vol",
        label: "音量",
        kind: "number",
        min: 0.1,
        max: 10,
        step: 0.1,
        default: 1,
        showWhen: { key: "voice.tts.active", value: ["", "minimax"] },
      },
      {
        path: "voice.tts.minimax.pitch",
        label: "音调",
        hint: "半音偏移:0 原声,正数更高更细,负数更低更沉,±12 一个八度",
        kind: "number",
        integer: true,
        min: -12,
        max: 12,
        default: 0,
        showWhen: { key: "voice.tts.active", value: ["", "minimax"] },
      },
      {
        path: "voice.tts.minimax.emotion",
        label: "情绪",
        kind: "select",
        choices: [
          { value: "", label: "模型自定" },
          "happy", "sad", "angry", "fearful", "disgusted", "surprised", "calm", "fluent", "whisper",
        ],
        default: "",
        showWhen: { key: "voice.tts.active", value: ["", "minimax"] },
      },
      {
        path: "voice.tts.minimax.language_boost",
        label: "语种增强",
        kind: "select",
        choices: ["auto", "Chinese", "Chinese,Yue", "English", "Japanese", "Korean"],
        default: "auto",
        showWhen: { key: "voice.tts.active", value: ["", "minimax"] },
      },
      {
        path: "voice.tts.mimo.api_key",
        label: "MiMo API key",
        hint: "platform.xiaomimimo.com 的 key(TTS 系列限时免费);支持 $env:VAR 引用",
        kind: "text",
        mono: true,
        default: "",
        nullable: true,
        showWhen: { key: "voice.tts.active", value: "mimo" },
      },
      {
        path: "voice.tts.mimo.base_url",
        label: "MiMo 接口地址",
        kind: "text",
        mono: true,
        default: "https://api.xiaomimimo.com/v1",
        showWhen: { key: "voice.tts.active", value: "mimo" },
      },
      {
        path: "voice.tts.mimo.model",
        label: "MiMo 模型",
        hint: "mimo-v2.5-tts 用预置音色;voicedesign 按「指令」里的描述造音色;voiceclone 按参考音频克隆",
        kind: "select",
        choices: ["mimo-v2.5-tts", "mimo-v2.5-tts-voicedesign", "mimo-v2.5-tts-voiceclone"],
        default: "mimo-v2.5-tts",
        showWhen: { key: "voice.tts.active", value: "mimo" },
      },
      {
        path: "voice.tts.mimo.voice",
        label: "MiMo 音色",
        hint: "只对 mimo-v2.5-tts 生效",
        kind: "select",
        choices: [
          { value: "mimo_default", label: "MiMo 默认" },
          { value: "冰糖", label: "冰糖 · 中文女声" },
          { value: "茉莉", label: "茉莉 · 中文女声" },
          { value: "苏打", label: "苏打 · 中文男声" },
          { value: "白桦", label: "白桦 · 中文男声" },
          { value: "Mia", label: "Mia · 英文女声" },
          { value: "Chloe", label: "Chloe · 英文女声" },
          { value: "Milo", label: "Milo · 英文男声" },
          { value: "Dean", label: "Dean · 英文男声" },
        ],
        default: "mimo_default",
        showWhen: { key: "voice.tts.active", value: "mimo" },
      },
      {
        path: "voice.tts.mimo.style",
        label: "MiMo 风格标签",
        hint: "加在文本开头的标签,如 温柔 / 开心 / 慵懒 / 东北话,多个用空格隔开;空 = 不加",
        kind: "text",
        default: "",
        showWhen: { key: "voice.tts.active", value: "mimo" },
      },
      {
        path: "voice.tts.mimo.prompt",
        label: "MiMo 提示词",
        hint: "一句自然语言写语速、语气、角色,如「语速稍快,像在跟朋友聊天」(MiMo 没有数值语速);voicedesign 模型下这里写音色描述(必填)",
        kind: "text",
        default: "",
        showWhen: { key: "voice.tts.active", value: "mimo" },
      },
      {
        path: "voice.tts.mimo.sample_audio",
        label: "MiMo 参考音频",
        hint: "voiceclone 模型用:本机 wav / mp3 路径,base64 后不超过 10MB",
        kind: "text",
        mono: true,
        default: "",
        nullable: true,
        showWhen: { key: "voice.tts.active", value: "mimo" },
      },
      {
        path: "voice.tts.preview_text",
        label: "试听语句",
        kind: "text",
        default: "今天也是充满希望的一天",
      },
      {
        path: "voice.tts.max_chars",
        label: "播报字数上限",
        hint: "播报文本超出即截断;模型的 <speak> 口语版通常在两三句以内",
        kind: "number",
        integer: true,
        min: 20,
        default: 300,
      },
      {
        path: "voice.notify_reply_chars",
        label: "完成通知摘要字数",
        kind: "number",
        integer: true,
        min: 0,
        unit: "字",
        default: 120,
      },
      {
        path: "voice.dictation_auto_submit",
        label: "REPL 听写直接发送",
        hint: "关=填进输入框等回车",
        kind: "toggle",
        default: false,
      },
    ],
  },
  {
    id: "notifications",
    title: "通知",
    tab: "语音与通知",
    fields: [
      {
        path: "notifications.enabled",
        label: "桌面通知",
        hint: "REPL 窗口有焦点时一律不弹",
        kind: "toggle",
        default: true,
      },
      {
        path: "notifications.on_turn_complete",
        label: "回复完成时通知",
        kind: "toggle",
        default: true,
      },
      {
        path: "notifications.job_writeback_to_terminal",
        label: "后台任务写回终端",
        hint: "shellhook 触发的任务完成后写回原终端,写不了退化为通知",
        kind: "toggle",
        default: true,
      },
    ],
  },
  {
    id: "prompt",
    title: "人格提醒",
    tab: "对话",
    fields: [
      {
        path: "prompt.persona_reminder",
        label: "防失忆提醒",
        hint: "每隔若干轮化石注入一次人格提醒",
        kind: "toggle",
        default: false,
      },
      {
        path: "prompt.persona_reminder_interval",
        label: "提醒间隔轮数",
        hint: "A/B 实测 3 最稳,调大风格会掉",
        kind: "number",
        integer: true,
        min: 1,
        unit: "轮",
        default: 3,
      },
    ],
  },
  {
    id: "embedding",
    title: "Embedding",
    tab: "记忆",
    fields: [
      {
        path: "embedding.enabled",
        label: "启用语义检索",
        hint: "关键词检索之上的辅助排序,用于知识库、记忆联想、表情包、被淘汰上下文;关掉只剩关键词",
        kind: "toggle",
        default: true,
      },
      {
        path: "embedding.backend",
        label: "后端",
        hint: "auto = 配了远程模型就用远程,否则用内置本地模型",
        kind: "select",
        options: [
          { value: "auto", label: "自动" },
          { value: "local", label: "本地模型(ONNX Runtime)" },
          { value: "remote", label: "远程 /embeddings 接口" },
        ],
        default: "auto",
      },
      {
        path: "embedding.local_model",
        label: "本地模型",
        hint: "内置 bge-small-zh-v1.5-int8;可填 assets/models 下的其它目录名或绝对路径。需要系统装有 onnxruntime(Arch: onnxruntime-cpu)",
        kind: "text",
        default: "bge-small-zh-v1.5-int8",
      },
      {
        path: "embedding.idle_unload_seconds",
        label: "本地模型空闲卸载",
        hint: "本地推理跑在独立子进程里,空闲这么久后退出,不占内存",
        kind: "number",
        integer: true,
        min: 5,
        unit: "秒",
        default: 600,
      },
      {
        path: "embedding",
        label: "远程 Embedding 供应商/模型",
        hint: "留空 = 不用远程;配了且后端为 auto 时优先于本地模型",
        kind: "model-ref",
        providerKey: "embedding.provider_id",
        modelKey: "embedding.model",
        capability: "embedding",
        default: { provider_id: "", model: "" },
      },
      {
        path: "embedding.timeout_seconds",
        label: "超时秒数",
        kind: "number",
        integer: true,
        min: 1,
        unit: "秒",
        default: 60,
      },
      {
        path: "embedding.min_score",
        label: "最低相似度(远程)",
        hint: "余弦相似度低于此不算命中;本地模型用自己 manifest.json 里的下限",
        kind: "number",
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.35,
      },
    ],
  },
  {
    id: "cache",
    title: "缓存",
    tab: "记忆",
    fields: [
      {
        path: "cache.request_log",
        label: "请求缓存记账日志",
        hint: "每次请求一行 token 数字,不含提示词文本",
        kind: "toggle",
        default: true,
      },
      {
        path: "cache.request_log_retention_days",
        label: "记账日志保留天数",
        kind: "number",
        integer: true,
        min: 0,
        unit: "天",
        default: 14,
      },
    ],
    advanced: [
      {
        path: "cache.keepalive_seconds",
        label: "空闲保活间隔",
        hint: "等待用户时定期重发前缀保住热缓存;0 = 关闭",
        kind: "number",
        integer: true,
        min: 0,
        unit: "秒",
        default: 0,
      },
      {
        path: "cache.keepalive_max_pings",
        label: "每轮最多保活次数",
        kind: "number",
        integer: true,
        min: 0,
        unit: "次",
        default: 20,
      },
      {
        path: "cache.write_grace_ms",
        label: "缓存写入等待",
        hint: "连续工具请求之间至少间隔多久;0 = 不等",
        kind: "number",
        integer: true,
        min: 0,
        unit: "毫秒",
        default: 0,
      },
    ],
  },
  {
    id: "accounts",
    title: "成员账号",
    tab: "账号与平台",
    fields: [
      {
        path: "accounts.member_personas",
        label: "成员可以创建自己的人格",
        hint: "关掉后成员只能用共享的 顾清影",
        kind: "toggle",
        default: true,
      },
      {
        path: "accounts.member_plugins",
        label: "成员人格可启用的插件",
        hint: "留空 = 全部。可选 id:files, album, usage_query, alarm, exchange_rate, map, express, archlinux, api_quota, print_image, memes, platform_outreach, web_images, image_generation, knowledge_base, ledger, scripts, mcp",
        kind: "string-list",
        nullable: true,
        default: null,
      },
    ],
  },
  {
    id: "platforms",
    title: "通讯平台",
    tab: "账号与平台",
    fields: [
      {
        path: "platforms.command_prefix",
        label: "命令触发前缀",
        hint: "1–32 字符,不含空白",
        kind: "text",
        default: "/",
      },
      {
        path: "platforms.max_tool_rounds",
        label: "最大工具轮数",
        hint: "平台回合的工具轮数上限,0 = 不限",
        kind: "number",
        integer: true,
        min: 0,
        unit: "轮",
        default: 32,
      },
      {
        path: "platforms.terminal_outreach",
        label: "允许 AI 从终端发消息到通讯平台",
        hint: "开启后终端 / WebUI / shellhook 会话里有 send_qq_message 工具;收件人只能是管理员 QQ 号(按别名列出),第一个为主管理员",
        kind: "toggle",
        default: true,
      },
    ],
  },
];
