// ---------------------------------------------------------------------
// QQ 平台(path 相对 platforms.qq)
// ---------------------------------------------------------------------
const sessionLimitsDefault = { running: 8, queued: 16 };

const qq = {
  connection: [
    { path: "enabled", label: "是否启用", kind: "toggle", default: false },
    {
      path: "reverse_ws_port",
      label: "反向 WebSocket 端口",
      kind: "number",
      integer: true,
      min: 1,
      max: 65535,
      default: 8300,
    },
    {
      path: "access_token",
      label: "反向 WebSocket 验证 Token",
      hint: "空 Token 只接受本机回环连接",
      kind: "secret",
      default: "",
    },
    {
      path: "asset_base_url",
      label: "文件访问基础 URL",
      hint: "NapCat 取临时文件用的公网地址,空 = 自动推导",
      kind: "text",
      default: "",
    },
    {
      path: "max_reply_chars",
      label: "单条回复最大字数",
      hint: "超过则分段发送,0 = 不分段",
      kind: "number",
      integer: true,
      min: 0,
      unit: "字符",
      default: 3000,
    },
    {
      path: "user_identification",
      label: "用户识别",
      hint: "把发送者稳定 id 放进系统上下文",
      kind: "toggle",
      default: true,
    },
    { path: "show_group_name", label: "显示群名称", kind: "toggle", default: true },
    {
      path: "memory.write_enabled",
      label: "写入人格记忆",
      hint: "平台会话是否允许写记忆库",
      kind: "toggle",
      default: true,
    },
    {
      path: "group_intermediate_messages",
      label: "群聊是否输出中间消息",
      hint: "每轮模型文本作为单独消息发出",
      kind: "toggle",
      default: false,
    },
    {
      path: "private_intermediate_messages",
      label: "私聊是否输出中间消息",
      kind: "toggle",
      default: true,
    },
  ],
  access: [
    {
      path: "admin_users",
      label: "允许使用终端的管理员 QQ 号",
      kind: "id-list",
      default: [],
    },
    {
      path: "owner_users",
      label: "主人 QQ 号",
      hint: "你本人的号，权限最高：自动算管理员（不用再填进上面的管理员），不能被拉黑，点赞等功能不受白名单限制。私聊里还和终端、网页共用同一份记忆并带上你的用户资料",
      kind: "id-list",
      default: [],
    },
    {
      path: "admin_aliases",
      label: "管理员别名",
      hint: "键 = QQ 号,值 = 别名;AI 从终端发消息时按别名选收件人",
      kind: "kv",
      keyPlaceholder: "QQ 号",
      valuePlaceholder: "别名",
      default: {},
    },
    {
      path: "allow_non_admin_host_tools",
      label: "是否允许非管理员使用电脑",
      hint: "仅对私聊白名单内的非管理员放开主机工具",
      kind: "toggle",
      default: false,
    },
    {
      path: "private_chats.whitelist",
      label: "私聊白名单",
      hint: "白名单私聊不受准入限流",
      kind: "id-list",
      default: [],
    },
    {
      path: "private_chats.friend_requests_require_private_whitelist",
      label: "仅私聊白名单能加好友",
      kind: "toggle",
      default: true,
    },
    {
      path: "private_chats.allow_non_whitelist",
      label: "是否允许非白名单私聊",
      kind: "toggle",
      default: true,
    },
    {
      path: "private_chats.non_whitelist_rate_limit",
      label: "非白名单私聊限流",
      hint: "按单个私聊计;条数 0 = 不限,窗口 1–86400 秒",
      kind: "rate-limit",
      default: { max_messages: 5, window_seconds: 300 },
    },
    {
      path: "sleep_hours",
      label: "睡眠时间",
      hint: "HH:MM-HH:MM,可跨午夜(如 23:00-07:00),留空 = 不睡;时段内只有管理员(私聊/群聊)和私聊白名单(仅私聊)的消息还会叫醒她,其余消息一律当没看见",
      kind: "text",
      mono: true,
      placeholder: "23:00-07:00",
      default: "",
    },
    {
      path: "group_chats.whitelist",
      label: "群聊白名单",
      kind: "id-list",
      default: [],
    },
    {
      path: "group_chats.trigger_keywords",
      label: "额外群聊触发关键词",
      hint: "@ 始终有效;每项 ≤128 字符",
      kind: "string-list",
      default: [],
    },
    {
      path: "group_chats.whitelist_rate_limit",
      label: "白名单群聊限流",
      hint: "同一群所有发送者共享",
      kind: "rate-limit",
      default: { max_messages: 30, window_seconds: 60 },
    },
    {
      path: "group_chats.allow_non_whitelist",
      label: "是否允许非白名单群聊",
      kind: "toggle",
      default: true,
    },
    {
      path: "group_chats.non_whitelist_rate_limit",
      label: "非白名单群聊限流",
      kind: "rate-limit",
      default: { max_messages: 5, window_seconds: 300 },
    },
  ],
  limits: [
    {
      path: "session_parallel",
      label: "会话内并行",
      hint: "关闭 = 同一会话串行,一次只答一条",
      kind: "toggle",
      default: false,
    },
    {
      path: "session_limits",
      label: "会话内并行数量",
      hint: "运行 1–16,等待 0–64;仅并行开启时生效",
      kind: "session-limits",
      default: sessionLimitsDefault,
    },
    {
      path: "private_chats.session_limits",
      label: "私聊并发覆盖",
      hint: "留空 = 继承 QQ 默认",
      kind: "session-limits",
      optional: true,
      default: null,
    },
    {
      path: "group_chats.session_limits",
      label: "群聊并发覆盖",
      hint: "留空 = 继承 QQ 默认",
      kind: "session-limits",
      optional: true,
      default: null,
    },
    {
      path: "group_context.on_overflow",
      label: "群聊上下文溢出策略",
      hint: "群聊建议 pop:摘要会毁掉引用指向的记录",
      kind: "select",
      choices: OVERFLOW_CHOICES,
      default: "pop",
    },
    {
      path: "group_context.trim_batch_ratio",
      label: "群聊单次丢弃比例",
      hint: "一次让出的窗口占比;0 = 继承全局",
      kind: "number",
      min: 0,
      max: 1,
      step: 0.05,
      default: 0.5,
    },
  ],
  models: [
    {
      path: "text_models",
      label: "平台文本池",
      hint: "QQ 全平台的文本池;不设则继承全局文本池",
      kind: "pool-ref",
      parentLabel: "全局池",
      parentIsGlobal: true,
      default: "inherit",
    },
    {
      path: "multimodal_models",
      label: "平台多模态池",
      hint: "不设则继承全局多模态池;须支持图片输入,不能指向分级档",
      kind: "pool-ref",
      parentLabel: "全局池",
      parentIsGlobal: true,
      capability: "image",
      default: "inherit",
    },
    {
      path: "non_whitelist_text_models",
      label: "非白名单文本",
      hint: "非白名单私聊/群聊用;不设则继承平台文本池",
      kind: "pool-ref",
      parentLabel: "平台池",
      default: "inherit",
    },
  ],
  routes: {
    title: "私聊/群聊专属配置",
    fields: [
      {
        key: "conversation.kind",
        label: "会话类型",
        kind: "select",
        choices: [
          { value: "private", label: "私聊" },
          { value: "group", label: "群聊" },
        ],
        default: "group",
      },
      {
        key: "conversation.id",
        label: "QQ 号 / 群号",
        hint: "正整数",
        kind: "text",
        default: "",
      },
      {
        key: "persona.mode",
        label: "覆盖 AI 人格",
        kind: "select",
        choices: [
          { value: "inherit", label: "继承当前人格" },
          { value: "gqy", label: "内置 顾清影" },
          { value: "custom", label: "指定人格文件" },
        ],
        default: "inherit",
      },
      {
        key: "persona.name",
        label: "人格文件名",
        hint: "prompts 目录下的 .md 文件名",
        kind: "text",
        showWhen: { key: "persona.mode", value: "custom" },
        default: "",
      },
      {
        key: "text_models",
        label: "文本模型池",
        hint: "留空 = 按下方继承来源",
        kind: "model-pool",
        optional: true,
        default: null,
      },
      {
        key: "text_models_inheritance",
        label: "文本池继承来源",
        hint: "仅在未设置文本模型池时生效",
        kind: "select",
        choices: [
          { value: "platform", label: "继承 QQ 平台池" },
          { value: "global", label: "继承全局池" },
        ],
        default: "platform",
      },
      {
        key: "multimodal_models",
        label: "多模态模型池",
        hint: "留空 = 按下方继承来源;须支持图片输入",
        kind: "model-pool",
        optional: true,
        capability: "image",
        default: null,
      },
      {
        key: "multimodal_models_inheritance",
        label: "多模态池继承来源",
        kind: "select",
        choices: [
          { value: "platform", label: "继承 QQ 平台池" },
          { value: "global", label: "继承全局池" },
        ],
        default: "platform",
      },
      {
        key: "extra_prompt",
        label: "额外提示词",
        hint: "≤200000 字符",
        kind: "textarea",
        default: "",
      },
      {
        key: "session_limits",
        label: "覆盖并发配置",
        hint: "留空 = 继承",
        kind: "session-limits",
        optional: true,
        default: null,
      },
      {
        key: "probability_reply",
        label: "概率主动回复",
        hint: "只管主动回复判断里的概率抽样;@、关键词、引用、接话、覆盖顶替和群管审核不受影响",
        kind: "select",
        choices: [
          { value: "", label: "继承插件设置" },
          { value: "on", label: "开" },
          { value: "off", label: "关(不做概率抽样)" },
        ],
        default: "",
        nullable: true,
      },
    ],
  },
};
